# Generated by Django 5.1.7 on 2025-07-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_consume_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consume',
            name='food_consumed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.food'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(help_text='Total calories'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(help_text='Carbohydrates in grams'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.FloatField(help_text='Fats in grams'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(help_text='Protein in grams'),
        ),
    ]
